services:
  postgres:
    ports: ["5432:5432"]
  redis:
    ports: ["6379:6379"]
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio123}
    command: server /data --console-address ":9001"
    volumes:
      - ./data/minio:/data
    restart: unless-stopped
    ports: ["9000:9000","9001:9001"]

  rabbitmq:
    ports: [ "5672:5672","15672:15672" ]

  ml:
    ports: [ "127.0.0.1:8001:8000" ]