spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/calendarbox_db
    username: calendarbox_user
    password: calendarbox_password
    driver-class-name: org.postgresql.Driver
  messages:
    basename: ValidationMessages
    encoding: UTF-8
  main:
    web-application-type: servlet


  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  flyway:
    enabled: true
    baseline-on-migrate: true

  rabbitmq:
    host: localhost
    port: 5672
    username: app
    password: apppass

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG

kakao:
  client_id: 72fecab83ee9fd949f17b58c0bdc474d
  redirect_uri: http://localhost:8080/api/auth/kakao/callback

naver:
  search:
    client-id: 3ZWem3_2PxmTfa8HPT7K
    client-secret: vSGs1rH3R4
  ocr:
    invoke-url: https://h3viu0bk3j.apigw.ntruss.com/custom/v1/47296/a2428e41d80824e2918a5b78aaa6279b416eeaa31fa59aa031978cbd07ed0362/document/receipt
    secret-key: SGRNS0FSakFDYWVKbm5TeWlNdUxISE9sQmNER3pqaFo=


auth:
  jwt:
    issuer: calendarbox
    access:
      secret: ${JWT_ACCESS_SECRET:local-dev-access-secret-32bytes-minimum}
      ttl-minutes: 30
    refresh:
      secret: ${JWT_REFRESH_SECRET:local-dev-refresh-secret-32bytes-minimum}
      ttl-minutes: 43200   # 14 days
    signup:
      secret: ${JWT_SIGNUP_SECRET:local-dev-signup-secret-32bytes-minimum}
      ttl-minutes: 30

security:
  cors:
    allowed-origins: "http://localhost:3000,https://your-frontend.com"

app:
  s3:
    bucket: calendarbox
    endpoint: http://localhost:9000
    region: us-east-1
    accessKey: minio
    secretKey: minio123
    usePathStyle: true
    presignMinutes: 5
    thumbPrefix: "thumb/256"

gemini:
  api-key: AIzaSyCaEfYxbI3-wgFzQ8W287bj_R9iipRajjw

embedding:
  python:
    url: http://localhost:8000/embed
  model-version: "st:all-MiniLM-L6-v2"

springdoc:
  api-docs:
    path: /api/v3/api-docs
  swagger-ui:
    path: /api/docs
    url: /api/v3/api-docs
    disable-swagger-default-url: true
  default-flat-param-object: true