spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/calendarbox_db
    username: calendarbox_user
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  messages:
    basename: ValidationMessages
    encoding: UTF-8
  main:
    web-application-type: servlet

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  data:
    redis:
      host: 127.0.0.1
      port: 6379

  flyway:
    enabled: true
    baseline-on-migrate: true

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: app
    password: apppass
    listener:
      simple:
        prefetch: 1

server:
  forward-headers-strategy: framework

management:
  server:
    address: 127.0.0.1
    port: 9091

  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: when_authorized

logging:
  level:
    root: INFO
    com.calendarbox: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    reactor.netty.http.client: DEBUG
    org.hibernate.SQL: DEBUG

kakao:
  client_id: ${KAKAO_CLIENT_ID}
  redirect_uri: ${KAKAO_REDIRECT_URI}  # 예: https://your-domain.com/auth/kakao/callback

naver:
  search:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
  ocr:
    invoke-url: ${OCR_INVOKE_URL}
    secret-key: ${OCR_SECRET_KEY}

auth:
  jwt:
    issuer: calendarbox
    access:
      secret: ${JWT_ACCESS_SECRET}
      ttl-minutes: 1440
    refresh:
      secret: ${JWT_REFRESH_SECRET}
      ttl-minutes: 43200  # 30 days
    signup:
      secret: ${JWT_SIGNUP_SECRET}
      ttl-minutes: 30

security:
  cors:
    allowed-origins: "https://your-frontend.com,http://localhost:3000,http://ec2-13-124-26-129.ap-northeast-2.compute.amazonaws.com,https://calendarbox.life" # 후에 ngrok 대신 우리 도메인 주소 기입

app:
  s3:
    bucket: ${S3_BUCKET}
    region: ${S3_REGION}
    endpoint:
    accessKey:
    secretKey:
    usePathStyle: false
    presignMinutes: 5
    thumbPrefix: "thumb/256"


gemini:
  api-key: ${GEMINI_API_KEY}

embedding:
  python:
    url: ${ML_URL}
  model-version: "st:all-MiniLM-L6-v2"

springdoc:
  api-docs:
    path: /api/v3/api-docs
  swagger-ui:
    path: /api/docs
    url: /api/v3/api-docs
    disable-swagger-default-url: true
  default-flat-param-object: true

